### ISSUE TITLE
Plugin for 4.13 editor builds,  after modifying the build.cs for BLuI but fails to build for package

### ISSUE THREAD

**Issue by WiccyShackleton** [AaronShea/BLUI#88]
hi,   I recently upgraded my project to version 4.13,  but now BLUI is giving errors when packaging the project - the build fails.  It only does this with the BLUI plugin enabled. I get this error in the output log:

UATHelper: Packaging (Linux): Running AutomationTool...
UATHelper: Packaging (Linux): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject="C:/Users/danny/Documents/Unreal Projects/MyProject2/MyProject2.uproject" BuildCookRun -nocompileeditor -nop4 -project="C:/Users/danny/Documents/Unreal Projects/MyProject2/MyProject2.uproject" -cook -stage -archive -archivedirectory="D:/MyProject2/New folder" 
-package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Linux -build -CrashReporter -utf8output -compile
UATHelper: Packaging (Linux): Automation.Process: Setting up command environment.
UATHelper: Packaging (Linux): ScriptCompiler.FindAndCompileScriptModules: Compiling scripts.
UATHelper: Packaging (Linux): MSBuild:   DotNETUtilities -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\DotNETUtilities.dll
UATHelper: Packaging (Linux): MSBuild:   UnrealBuildTool -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe
UATHelper: Packaging (Linux): MSBuild:   AutomationUtils.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationUtils.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   AllDesktop.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AllDesktop\AllDesktop.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   GUBP.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\GUBP.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   Localization.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Localization.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   OneSkyLocalization.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\OneSkyLocalization.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   AutomationScripts.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AutomationScripts.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   Android.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android\Android.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   BuildGraph.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\BuildGraph.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   HTML5.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\HTML5\HTML5.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   IOS.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\IOS\IOS.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   Linux.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Linux\Linux.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   Mac.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Mac\Mac.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   TVOS.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\TVOS\TVOS.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   Win.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Win.Automation.dll
UATHelper: Packaging (Linux): MSBuild:   XLocLocalization.Automation -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\XLocLocalization.Automation.dll
UATHelper: Packaging (Linux): CommandUtils.Run: Run: Took 4.448897s to run MSBuild.exe, ExitCode=0
UATHelper: Packaging (Linux): BuildCookRun.SetupParams: Setting up ProjectParams for C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject
UATHelper: Packaging (Linux): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Linux): CommandUtils.Run: Run: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe D:/UE4/UE4.13/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj /verbosity:minimal /nologo /target:Rebuild /property:Configuration=Development /property:Platform=AnyCPU
UATHelper: Packaging (Linux): MSBuild:   DotNETUtilities -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\DotNETUtilities.dll
UATHelper: Packaging (Linux): MSBuild:   UnrealBuildTool -> D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe
UATHelper: Packaging (Linux): CommandUtils.Run: Run: Took 1.6103707s to run MSBuild.exe, ExitCode=0
UATHelper: Packaging (Linux): CommandUtils.Run: Run: D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe MyProject2 Linux Development -Project="C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject"  "C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject"  -remoteini="C:\Users\danny\Documents\Unreal Proje
cts\MyProject2" -noxge -generatemanifest -NoHotReload
UATHelper: Packaging (Linux): CommandUtils.Run: Run: Took 2.7287596s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (Linux): CommandUtils.Run: Run: D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe MyProject2 Linux Development -Project="C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject"  "C:\Users\danny\Documents\Unreal Projects\MyProjec
UATHelper: Packaging (Linux): t2\MyProject2.uproject"  -remoteini="C:\Users\danny\Documents\Unreal Projects\MyProject2" -noxge -NoHotReload -ignorejunk
UATHelper: Packaging (Linux): UnrealBuildTool: Creating makefile for MyProject2 (project files are newer)
UATHelper: Packaging (Linux): UnrealBuildTool: Building UnrealHeaderTool...
UATHelper: Packaging (Linux): UnrealBuildTool: Creating makefile for UnrealHeaderTool (UnrealBuildTool.exe is newer)
UATHelper: Packaging (Linux): UnrealBuildTool: Target is up to date
UATHelper: Packaging (Linux): UnrealBuildTool: Parsing headers for MyProject2
UATHelper: Packaging (Linux): UnrealBuildTool:   Running UnrealHeaderTool "C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject" "C:\Users\danny\Documents\Unreal Projects\MyProject2\Intermediate\Build\Linux\B4D820EA\MyProject2\Development\MyProject2.uhtmanifest" -Log
UATHelper: Packaging (Linux): Cmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
UATHelper: Packaging (Linux): UnrealBuildTool: Reflection code generated for MyProject2 in 5.3862136 seconds
UATHelper: Packaging (Linux): UnrealBuildTool: Performing 7 actions (4 in parallel)
UATHelper: Packaging (Linux): UnrealBuildTool: [1/7] Compile Blu.generated.cpp
UATHelper: Packaging (Linux): UnrealBuildTool: [2/7] Compile Module.Blu.cpp
UATHelper: Packaging (Linux): UnrealBuildTool: [3/7] Compile Module.BluLoader.cpp
UATHelper: Packaging (Linux): UnrealBuildTool: [4/7] Compile UELinkerFixups.cpp
UATHelper: Packaging (Linux): UnrealBuildTool: [5/7] Archive libMyProject2-BluLoader.a
UATHelper: Packaging (Linux): UnrealBuildTool: [6/7] Archive libMyProject2-Blu.a
UATHelper: Packaging (Linux): UnrealBuildTool: [7/7] Link MyProject2
UATHelper: Packaging (Linux): UnrealBuildTool: C:/Users/danny/Documents/Unreal Projects/MyProject2/Plugins/BLUI/ThirdParty/cef/Linux/lib/libcef_dll_wrapper.a(transfer_util.cc.o): In function `transfer_string_map_contents(std::map<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16>, std::less<CefStringBase<CefStringTraitsUTF16> >, std::al
locator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > > const&, void*)':
UATHelper: Packaging (Linux): UnrealBuildTool: transfer_util.cc:(.text._Z28transfer_string_map_contentsRKSt3mapI13CefStringBaseI20CefStringTraitsUTF16ES2_St4lessIS2_ESaISt4pairIKS2_S2_EEEPv+0x2c): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)'
UATHelper: Packaging (Linux): UnrealBuildTool: C:/Users/danny/Documents/Unreal Projects/MyProject2/Plugins/BLUI/ThirdParty/cef/Linux/lib/libcef_dll_wrapper.a(transfer_util.cc.o): In function `transfer_string_multimap_contents(std::multimap<CefStringBase<CefStringTraitsUTF16>, CefString
UATHelper: Packaging (Linux): Base<CefStringTraitsUTF16>, std::less<CefStringBase<CefStringTraitsUTF16> >, std::allocator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > > const&, void*)':
UATHelper: Packaging (Linux): UnrealBuildTool: transfer_util.cc:(.text._Z33transfer_string_multimap_contentsRKSt8multimapI13CefStringBaseI20CefStringTraitsUTF16ES2_St4lessIS2_ESaISt4pairIKS2_S2_EEEPv+0x2c): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)'
UATHelper: Packaging (Linux): UnrealBuildTool: C:/Users/danny/Documents/Unreal Projects/MyProject2/Plugins/BLUI/ThirdParty/cef/Linux/lib/libcef_dll_wrapper.a(transfer_util.cc.o): In function `std::_Rb_tree_iterator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > std::_Rb_tree<CefStringBase<CefStringTraitsUTF16>, s
td::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> >, std::_Select1st<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > >, std::less<CefStringBase<CefStringTraitsUTF16> >, std::allocator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > >:
:_M_insert_<std::pair<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16> > >(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16> >&&)':
UATHelper: Packaging (Linux): UnrealBuildTool: transfer_util.cc:(.text._ZNSt8_Rb_treeI13CefStringBaseI20CefStringTraitsUTF16ESt4pairIKS2_S2_ESt10_Select1stIS5_ESt4lessIS2_ESaIS5_EE10_M_insert_IS3_IS2_S2_EEESt17_Rb_tree_iteratorIS5_EPSt18_Rb_tree_node_baseSH_OT_[_ZNSt8_Rb_treeI13CefStringBaseI20CefStringTraitsUTF16ESt4pairIKS2_S2_ESt10_Select1stIS5_ESt4lessIS
2_ESaIS5_EE10_M_insert_IS3_IS2_S2_EEESt17_Rb_tree_iteratorIS5_EPSt18_Rb_tree_node_baseSH_OT_]+0x15e): undefined reference to `std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
UATHelper: Packaging (Linux): UnrealBuildTool: C:/Users/danny/Documents/Unreal Projects/MyProject2/Plugins/BLUI/ThirdParty/cef/Linux/lib/libcef_dll_wrapper.a(transfer_util.cc.o): In function `transfer_string_map_contents(void*, std::map<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16>, std::less<CefStringBase<CefStringTraitsUTF16> >, 
std::allocator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > >&)':
UATHelper: Packaging (Linux): UnrealBuildTool: transfer_util.cc:(.text._Z28transfer_string_map_contentsPvRSt3mapI13CefStringBaseI20CefStringTraitsUTF16ES3_St4lessIS3_ESaISt4pairIKS3_S3_EEE+0x201): undefined reference to `std::_Rb_tree_decrement(std::_Rb_tree_node_base*)'
UATHelper: Packaging (Linux): UnrealBuildTool: clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Linux): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: C:\Users\danny\Documents\Unreal Projects\MyProject2\Binaries\Linux\MyProject2
UATHelper: Packaging (Linux): UnrealBuildTool: Total build time: 63.74 seconds
UATHelper: Packaging (Linux): CommandUtils.Run: Run: Took 63.8208548s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Linux): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): D:\UE4\UE4.13\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe MyProject2 Linux Development -Project="C:\Users\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject"  "C:\U
sers\danny\Documents\Unreal Projects\MyProject2\MyProject2.uproject"  -remoteini="C:\Users\danny\Documents\Unreal Projects\MyProject2" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.11.02-14.29.44.txt' 
UATHelper: Packaging (Linux):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessUtils.cs:line 883
UATHelper: Packaging (Linux):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessU
tils.cs:line 836
UATHelper: Packaging (Linux):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 51
UATHelper: Packaging (Linux):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 89
UATHelper: Packaging (Linux):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars) in D:\UE4\UE4
.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\UE4Build.cs:line 362
UATHelper: Packaging (Linux):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTa
rgetToManifest) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\UE4Build.cs:line 1460
UATHelper: Packaging (Linux):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask) in d:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\BuildProjectCommand.Automation.cs:line 172
UATHelper: Packaging (Linux):    at BuildCookRun.DoBuildCookRun(ProjectParams Params) in d:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 211
UATHelper: Packaging (Linux):    at AutomationTool.BuildCommand.Execute() in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 27
UATHelper: Packaging (Linux):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 547
UATHelper: Packaging (Linux):    at AutomationTool.Automation.Process(String[] Arguments) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 517
UATHelper: Packaging (Linux):    at AutomationTool.Program.MainProc(Object Param) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 135
UATHelper: Packaging (Linux):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param) in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 704
UATHelper: Packaging (Linux):    at AutomationTool.Program.Main() in D:\UE4\UE4.13\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 59
UATHelper: Packaging (Linux): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Linux): BUILD FAILED
PackagingResults:Error: Error Unknown Error

**Comment by Deams51** [comment]
Having the same issue here. 
@AaronShea I believe ue4 is using a new version of clang and libs, could you share your compile setup for the CEF lib so that we can update the Linux libraries? 
Or if you have the time, feel free to update the libs directly. ;)
