### ISSUE TITLE
Error during BLUI setup

### ISSUE THREAD

**Issue by Dorkside** [AaronShea/BLUI#96]
THis error occurred when trying to Generate Visual Studio project files

```
Running D:/Tools/Epic Games/4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="D:/Documents/Unreal Projects/BLUITest/BLUITest.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
ERROR: Unable to instantiate instance of 'Blu' object type from compiled assembly 'BLUITestModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.  Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requirements.  The CLR exception details may provide more information:  System.Reflection.TargetInvocationException: Une exception a ?t? lev?e par la cible d'un appel. ---> System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'acc?s 'D:\Documents\Unreal Projects\BLUITest\Plugins\BLUI\ThirdParty\cef\Win\shipping'.
   ? System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ? System.IO.FileSystemEnumerableIterator`1.CommonInit()
   ? System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   ? Blu..ctor(TargetInfo Target) dans d:\Documents\Unreal Projects\BLUITest\Plugins\BLUI\Source\Blu\Blu.Build.cs:ligne 58
   --- Fin de la trace de la pile d'exception interne ---
   ? System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   ? System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   ? System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   ? System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   ? System.Activator.CreateInstance(Type type, Object[] args)
   ? UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, TargetInfo Target, FileReference& ModuleFileName)
```

Any idea what the cause is ?

**Comment by TTimo** [comment]
I think the critical piece of info there is 'D:\Documents\Unreal Projects\BLUITest\Plugins\BLUI\ThirdParty\cef\Win\shipping' not found.

It's a submodule, which you may need to compile first? (I'm just guessing I haven't tried using blui yet)

**Comment by dannyflint** [comment]
When attempting to generate the Visual Studio files I get an identical error. I am trying to open the demo file, with the supposed UE4.1.5 update. Dorkside, if you managed to fix this please come to my aid

```
Running K:/Programs/EPIC/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe -projectfiles -project="K:/BLUIDemo/BLUIDemo.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
ERROR: Unable to instantiate instance of 'Blu' object type from compiled assembly 'BLUIDemoModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requirements. The CLR exception details may provide more information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'K:\BLUIDemo\Plugins\BLUI\ThirdParty\cef\Win\shipping'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator`1.CommonInit()
at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
at Blu..ctor(TargetInfo Target) in k:\BLUIDemo\Plugins\BLUI\Source\Blu\Blu.Build.cs:line 58
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, Object[] args)
at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, TargetInfo Target, FileReference& ModuleFileName)
```

**Comment by TheModdersDen** [comment]
I'm having the same issue as well on the 4.16 preview 3 build. Any fix as of yet?

**Comment by dannyflint** [comment]
I just gave up eventually so if you figure it please let me.know. Thanks.

**Comment by zongtonggui** [comment]
Did you solve the problem? I'm having the same issue as well on the 4.15. @dannyflint @Dorkside

**Comment by Dorkside** [comment]
Not using BLUI anymore in my project, shifted to a very different setup combining UE4 and electron.
Just a hunch though, might be a space in the project path.

**Comment by zongtonggui** [comment]
@Dorkside I have solved this problem through the help of others。My English is not good, I hope you can understand my expression：

In BluManager.h, You should convert static variable to local variable。
static CefSettings settings;
static CefMainArgs main_args;

And in  BluManager.cpp     You should delete 
Cefsettings BluManager::settings;
CefMainArgs BluManager::main_args;

And In Blu.cpp ,You shoud revise the  StartupModule()  function like this：


	/** IModuleInterface implementation */
	virtual void StartupModule() override
	{
		CefString GameDirCef = *FPaths::ConvertRelativePathToFull(FPaths::GameDir() + "BluCache");
		FString ExecutablePath = FPaths::ConvertRelativePathToFull(FPaths::GameDir() + "Plugins/BLUI/ThirdParty/cef/");
		// Make the CefSettings and CefMainArgs local as they only need to be used in this function
		CefSettings settings;
		CefMainArgs main_args;

		// Setup the default settings for BluManager
		settings.windowless_rendering_enabled = true;
		settings.no_sandbox = true;
		settings.remote_debugging_port = 7777;


	#if PLATFORM_LINUX
		ExecutablePath = "./blu_ue4_process";
	#endif
	#if PLATFORM_MAC
		ExecutablePath += "Mac/shipping/blu_ue4_process.app/Contents/MacOS/blu_ue4_process";
	#endif
	#if PLATFORM_WINDOWS
		ExecutablePath += "Win/shipping/blu_ue4_process.exe";
	#endif

		CefString realExePath = *ExecutablePath;

		// Set the sub-process path
		CefString(&settings.browser_subprocess_path).FromString(realExePath);

		// Set the cache path
		CefString(&settings.cache_path).FromString(GameDirCef);

		// Make a new manager instance
		CefRefPtr<BluManager> BluApp = new BluManager();

		//CefExecuteProcess(BluManager::main_args, BluApp, NULL);
		CefInitialize(main_args, settings, BluApp, NULL);

		UE_LOG(LogBlu, Log, TEXT(" STATUS: Loaded"));
	}

**Comment by Dorkside** [comment]
Since I'm not using BLUI anymore could anyone having this problem confirm this works ?
I remember having read somehting like this indeed, might have solved the problem back then.
Thanks for the update anyways :-).
I'll close the post as soon as somebody confirms the solution.
Cheers

**Comment by dannyflint** [comment]
I'm on my way home from work now and will try and dig out my project and see if the solution works.

**Comment by dannyflint** [comment]
Zong, have you pulled the solution?

**Comment by zongtonggui** [comment]
I had two problems in my project. 
The first question is this one.But I forgot how it worked out .Maybe you should regenerate your project?
The second question is that  program starts for a long time after packing.I had solved second problems.

Would you like me to send you a correct project? It is set up well。

Let me look at the first question again.

**Comment by dannyflint** [comment]
Your English is fine. Thanks for that. Last night I spent some time getting it working in 4.16 using a fixed plugin shared in one of the other threads above this one. I haven't got interactivity working yet, but I can see webpages in UE4 ... I was hoping to look at that today

**Comment by zongtonggui** [comment]
Congratulations！Good luck~ It's not difficult, it just needs to overwrite slate.

**Comment by dannyflint** [comment]
Hey I managed to get your demo loading up the UI but again Im not really sure how to get.interactivity working. Any tips?

**Comment by zongtonggui** [comment]
@dannyflint Sorry, I did not see this information until now。In Level Blueprint,，You should do a Tick. In new widget Blueprint ,You can see the operation of loading the UI.If you want to interact, you should overload the event.
        I hope you have solved this problem.Very sorry, Git did not inform me of your reply.If you want to contact me faster, you can contact my email ：876993089@qq.com  or QQ 876993089.If I received the news, I would reply you as soon as possible.

**Comment by zongtonggui** [comment]
![override](https://user-images.githubusercontent.com/22297967/29821864-fa26ca20-8cfb-11e7-80ed-f68ee6e2b447.png) 

In UMG, overload the mouse  event   @dannyflint

**Comment by dannyflint** [comment]
Hi everyone,

I have it totally working. No time to post my projects but i hope too soon - thanks so much

________________________________
