### ISSUE TITLE
运行build.py时发生错误，请帮我看下什么错误，谢谢！

### ISSUE THREAD

**Issue by Simon-GitHub** [AaronShea/BLUI#97]
F:\builder>builder.py
Checking for: ['git', 'msbuild', 'cmake', 'python', 'patch']
Check for git
Check for msbuild
Check for cmake
Check for python
Check for patch
All good!
Cloning into 'blui'...
remote: Counting objects: 1140, done.
remote: Total 1140 (delta 0), reused 0 (delta 0), pack-reused 1140Receiving obje

Receiving objects: 100% (1140/1140), 223.42 KiB | 148.00 KiB/s, done.
Resolving deltas: 100% (587/587), done.
Cloning into 'browser'...
remote: Counting objects: 113, done.
remote: Total 113 (delta 0), reused 0 (delta 0), pack-reused 113Receiving object

Resolving deltas: 100% (46/46), done.
We're about to fetch and build Chromium and CEF!
This is going to take a while, please don't kill
the process until it's done.
Please input your Visual Studio Version (2012, 2013 etc): 2015
--> Creating directory F:\builder\cefbuild
--> Download Directory: F:\builder\cefbuild
--> Depot Tools Directory: F:\builder\cefbuild\depot_tools
--> Extracting https://storage.googleapis.com/chrome-infra/depot_tools.zip to F:
\builder\cefbuild\depot_tools.
--> Updating depot_tools
-------- Running "update_depot_tools.bat" in "F:\builder\cefbuild\depot_tools"..
.
Installing python 2.7.6...
Fetching from https://storage.googleapis.com/chrome-infra/python276_bin.zip
Bootstrapping cipd client for windows-386...
From https://chrome-infra-packages.appspot.com/client?platform=windows-386&vers
ion=git_revision:76eadcd75c5ad2638e1fc098f81748aad150c7c0
使用“2”个参数调用“DownloadFile”时发生异常:“无法连接到远程服务器”
所在位置 F:\builder\cefbuild\depot_tools\cipd.ps1:47 字符: 21
+     $wc.DownloadFile <<<< ($url, $client)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

无法将“F:\builder\cefbuild\depot_tools\.cipd_client.exe”项识别为 cmdlet、函数
、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，
然后重试。
所在位置 F:\builder\cefbuild\depot_tools\cipd.ps1:50 字符: 7
+ $_ = & <<<<  $client selfupdate -version "$cipdClientVer"
    + CategoryInfo          : ObjectNotFound: (F:\builder\cefb...cipd_client.e
   xe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

无法将“F:\builder\cefbuild\depot_tools\.cipd_client.exe”项识别为 cmdlet、函数
、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，
然后重试。
所在位置 F:\builder\cefbuild\depot_tools\cipd.ps1:56 字符: 2
+ & <<<<  $client @args
    + CategoryInfo          : ObjectNotFound: (F:\builder\cefb...cipd_client.e
   xe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Traceback (most recent call last):
  File "F:\builder\cefbuild\depot_tools\bootstrap\win\git_bootstrap.py", line 19
3, in <module>
    sys.exit(main(sys.argv[1:]))
  File "F:\builder\cefbuild\depot_tools\bootstrap\win\git_bootstrap.py", line 18
5, in main
    install_git(args, git_version, git_directory)
  File "F:\builder\cefbuild\depot_tools\bootstrap\win\git_bootstrap.py", line 11
5, in install_git
    '-Directory="%s"' % git_directory.replace('\\', '\\\\'),
  File "F:\builder\cefbuild\depot_tools\bootstrap\win\git_bootstrap.py", line 26
, in _check_call
    subprocess.check_call(argv, **kwargs)
  File "F:\builder\cefbuild\depot_tools\python276_bin\lib\subprocess.py", line 5
35, in check_call
    retcode = call(*popenargs, **kwargs)
  File "F:\builder\cefbuild\depot_tools\python276_bin\lib\subprocess.py", line 5
22, in call
    return Popen(*popenargs, **kwargs).wait()
  File "F:\builder\cefbuild\depot_tools\python276_bin\lib\subprocess.py", line 7
09, in __init__
    errread, errwrite)
  File "F:\builder\cefbuild\depot_tools\python276_bin\lib\subprocess.py", line 9
57, in _execute_child
    startupinfo)
WindowsError: [Error 2]
--> CEF Branch: 2623
--> CEF URL: https://bitbucket.org/chromiumembedded/cef.git
--> CEF Source Directory: F:\builder\cefbuild\cef
-------- Running "F:\builder\cefbuild\depot_tools\git.bat clone https://bitbucke
t.org/chromiumembedded/cef.git F:\builder\cefbuild\cef" in "F:\builder\cefbuild"
...
'F:\builder\cefbuild\depot_tools\git.bat' 不是内部或外部命令，也不是可运行的程序

或批处理文件。
Traceback (most recent call last):
  File "cefbuild.py", line 698, in <module>
    depot_tools_dir)
  File "cefbuild.py", line 55, in run
    shell=(sys.platform == 'win32'))
  File "D:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\builder\\cefbuild\\depot_tools\\gi
t.bat', 'clone', 'https://bitbucket.org/chromiumembedded/cef.git', 'F:\\builder\
\cefbuild\\cef']' returned non-zero exit status 1
Applying patches...
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- libcef/common/main_delegate.cc.orig        2015-02-12 17:38:40.000000000 +0
100
|+++ libcef/common/main_delegate.cc     2015-02-12 17:38:35.000000000 +0100
--------------------------
patch: **** Can't find file ./cefbuild/cef/libcef/common/main_delegate.cc : No s
uch file or directory
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- framework-Info.plist       2015-08-29 11:11:29.720900500 -0400
|+++ framework-Info_new.plist   2015-08-29 11:13:29.611784400 -0400
--------------------------
patch: **** Can't find file ./cefbuild/cef/libcef/resources/framework-Info.plist
 : No such file or directory
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- cef_base.h 2016-05-05 11:36:43.703458900 -0400
|+++ cef_base.h 2016-05-09 13:29:12.757864200 -0400
--------------------------
patch: **** Can't find file ./cefbuild/cef/include/cef_base.h : No such file or
directory
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- cef_thread_collision_warner.h      2016-05-05 11:36:52.804317800 -0400
|+++ cef_thread_collision_warner.h      2016-05-09 13:25:56.050338700 -0400
--------------------------
patch: **** Can't find file ./cefbuild/cef/include/base/cef_thread_collision_war
ner.h : No such file or directory
-- Building CEF and Chromium. This will take a while! --
--> Download Directory: F:\builder\cefbuild
--> Depot Tools Directory: F:\builder\cefbuild\depot_tools
--> CEF Branch: 2623
--> CEF URL: https://bitbucket.org/chromiumembedded/cef.git
--> CEF Source Directory: F:\builder\cefbuild\cef
--> CEF Output Directory: F:\builder\cefbuild\out_2623
--> Creating directory F:\builder\cefbuild\chromium
--> Writing file: F:\builder\cefbuild\chromium\.gclient
Traceback (most recent call last):
  File "cefbuild.py", line 799, in <module>
    raise Exception('Not a valid git checkout: %s' % (chromium_src_dir))
Exception: Not a valid git checkout: F:\builder\cefbuild\chromium\src
Traceback (most recent call last):
  File "F:\builder\builder.py", line 144, in <module>
    builder.build_browser()
  File "F:\builder\builder.py", line 78, in build_browser
    rmpath = glob.glob('./cefbuild/chromium/src/cef/binary_distrib/cef_binary_*6
4/cefsimple')[0]
IndexError: list index out of range

F:\builder>

**Comment by Simon-GitHub** [comment]
已解决，是未翻墙的问题。Thank you！
